name: Deploy Docker Image

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Pull Docker image
        run: sudo docker pull shahchhatru/lpbmis-frontend:latest

      - name: Stop and remove existing container if running
        run: |
          sudo docker stop lpbmis-frontend || true
          sudo docker rm lpbmis-frontend || true

      - name: Run new container
        run: |
          sudo docker run -d \
            --name lpbmis-frontend \
            -p 80:80 \
            shahchhatru/lpbmis-frontend:latest
