name: Deploy Docker Image

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Pull Docker image
        run: docker pull miroshpradhan/lpbmis-frontend:latest

      - name: Stop existing container
        run: |
          docker stop lpbmis-frontend || true
          docker rm lpbmis-frontend || true

      - name: Run new container
        run: |
          docker run -d --name lpbmis-frontend -p 80:80 miroshpradhan/lpbmis-frontend:latest
